[project]
name = "hdyndns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "requests>=2.32.3",
]
